app.controller("becomeproCtrl",['$scope','srvAuth','$sessionStorage','$location','$http','$rootScope','$filter','$mdDialog','$mdToast',function($scope,sAuth,$sessionStorage,$location,$http,$rootScope,$filter,$mdDialog,$mdToast){if(!$sessionStorage.user){$location.path('/login')}else if($sessionStorage.user&&$sessionStorage.whatChoice){$location.path('/member/'+$sessionStorage.whatChoice);}else if($sessionStorage.user&&!$sessionStorage.whatChoice){$location.path('/member/what-choice')}$scope.toggleFilterShow={};$scope.nowDate=new Date();$scope.showToast=function(string,number,callback){if(number>0){$mdToast.show($mdToast.simple().textContent(string+number).position('bottom','right').hideDelay(3000)).then(callback);}else{callback}}
$scope.svgs=[{svg:'delivery-truck.svg',service:'moving',polish_name:'Przeprowadzki'},{svg:'housekeeping.svg',service:'cleaning',polish_name:'Sprzątanie'},{svg:'package.svg',service:'assembly',polish_name:'Składanie mebli'},{svg:'repair.svg',service:'handyman',polish_name:'Złota rączka'},{svg:'trash.svg',service:'gardening',polish_name:'Ogrodnik'}]
$scope.currentNavItem='page2';$scope.addOffer=false;$scope.editOffer=false;$scope.addOfferStep=0;$scope.sStorage=$sessionStorage;$scope.addOfferTrigger=function(){$scope.addOffer=!$scope.addOffer;$scope.editOffer=false;}
$scope.editOfferTrigger=function(){$scope.editOffer=!$scope.editOffer;$scope.addOffer=false;}
$scope.addoffer={};$scope.fields=['handyman','cleaning','moving','assembly','gardening']
$scope.days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
$scope.addoffer.fieldsSelected=[];$scope.addoffer.daysSelected=[];$scope.forms={};$scope.toggle=function(item,list){var idx=list.indexOf(item);if(idx>-1){list.splice(idx,1);}else{list.push(item);}};$scope.getUserData=function(){$scope.dataLoading=true;$http({method:'POST',url:"https://robisie.co/api/index.php",data:{operation:'getuserdata',email:$sessionStorage.user.email}}).success(function(response){$scope.dataLoading=false;response.user_data[0].professional_availability_week=response.user_data[0].professional_availability_week.split(',');response.user_data[0].professional_field=response.user_data[0].professional_field.split(',');$scope.user=response.user_data[0];$scope.requests=response.user_data.request_r;$scope.pendingCounter=0;$scope.timeElapsedCounter=0;if($scope.requests){for(var i=0;i<$scope.requests.length;i++){if($scope.requests[i].status_request==='pending'){$scope.pendingCounter++;}if($scope.requests[i].status_request==='accept'&&$scope.requests[i].end_time_request<$scope.nowDate){$scope.timeElapsedCounter++;}}}$scope.showToast('Liczba oczekujących ofert: ',$scope.pendingCounter,function(){$scope.showToast('Liczba ofert po czasie: ',$scope.timeElapsedCounter)});}).error(function(data,status,headers,config){$scope.dataLoading=false;});}
$scope.getUserData()
$scope.editDataDialog=function(ev){$mdDialog.show({controller:'dialogEditDataCtrl',templateUrl:'js/views/editDataDialog.html',parent:angular.element(document.body),targetEvent:ev,fullscreen:$scope.customFullscreen,locals:{user:$sessionStorage.user}}).then(function(picture){if(!$scope.user.picture){$scope.user.picture=picture;}$scope.getUserData()});};$scope.uploadOffer=function(){$http({method:'POST',url:"https://robisie.co/api/index.php",data:{operation:'addoffer',email:$scope.sStorage.user.email,offer:$scope.addoffer}}).success(function(response){$scope.addoffer={}
$scope.forms.add_offer.$setUntouched()
if(response.result==='success'&&response.message==='Offer added Successfully'){$scope.addOfferMessage='Zgłoszenie zostało wysłane.'
$mdDialog.show($mdDialog.alert().parent(angular.element(document.querySelector('#popupContainer'))).clickOutsideToClose(true).title('Udało się!').textContent('Oferta została wysłana do zatwierdzenia!').ariaLabel('Alert Dialog Demo').ok('OK!'));}else{$scope.addOfferMessage='Nie udało się wysłać zgłoszenia.'}$scope.getUserData()
$scope.addOffer=false;}).error(function(data,status,headers,config){$scope.addoffer={}
$scope.forms.add_offer.$setUntouched()});}
$scope.showConfirm=function(ev){var confirm=$mdDialog.confirm().title('Na pewno chcesz skasować swoją ofertę?').textContent('Twoja oferta zostanie usunięta z listy profesjonalistów').ariaLabel('Lucky day').targetEvent(ev).ok('Tak').cancel('Nie');$mdDialog.show(confirm).then(function(){$http({method:'POST',url:"https://robisie.co/api/index.php",data:{operation:'deleteoffer',offer_id:$scope.user.offer_Id}}).success(function(response){$scope.getUserData();}).error(function(data,status,headers,config){});},function(){$scope.status='You decided to keep your debt.';});};$scope.answerOffer=function(request,answer){var request=request,answer=answer;var confirm=$mdDialog.confirm().title('Na pewno chcesz to zrobić?').ariaLabel('reject or accept').ok('Tak!').cancel('Nie!');$mdDialog.show(confirm).then(function(){$http({method:'POST',url:"https://robisie.co/api/index.php",data:{operation:'acceptreject',offer_id:request.id_Request,rejectOrAccept:answer}}).success(function(response){$scope.getUserData();}).error(function(data,status,headers,config){});},function(){$scope.status='You decided to keep your debt.';});}
$scope.getReviews=function(){$scope.reviewsLoading=true;$http({method:'POST',url:"https://robisie.co/api/index.php",data:{operation:'getproreview',email:$sessionStorage.user.email}}).success(function(response){$scope.becomeProReviews=response.reviews}).error(function(data,status,headers,config){});}
$scope.getReviews()
$scope.filterReviews=function(request,idRequest,index){function filterOut(argument){return function(element){return argument===element.idrequest}}$scope.returnedReview=$scope.becomeProReviews.filter(filterOut(idRequest));request.review=$scope.returnedReview;$scope.toggleFilterShow[index]=!$scope.toggleFilterShow[index];}
$scope.confirmDone=function(request,answer){var request=request,answer=answer;var confirm=$mdDialog.confirm().title('Na pewno chcesz to zrobić?').ariaLabel('reject or accept').ok('Tak!').cancel('Nie!');$mdDialog.show(confirm).then(function(){$http({method:'POST',url:"https://robisie.co/api/index.php",data:{operation:'confirmdonepro',offer_id:request.id_Request,doneOrNot:answer}}).success(function(response){$scope.getUserData();}).error(function(response){});},function(){});}}])